name: Publish via Web Deploy to SmarterASP.NET

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Checkout, Publish and Deploy to SmarterASP.NET
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x' # Cambia si usas otra versión
      - name: Clean 
        run: dotnet clean
        
      - name: Restore dependencies
        run: dotnet restore VotingSystem.csproj

      - name: Build project
        run: dotnet build --configuration Release VotingSystem.csproj

      - name: Publish project
        run: dotnet publish --configuration Release --output ./publish VotingSystem.csproj

      - name: Deploy to SmarterASP.NET
        uses: aarhusit/deploy@main
        with:
          csproj-filepath: VotingSystem.csproj
          website-name: daniel190-001-site1
          server-computer-name: https://win1135.site4now.net:8172
          server-username: daniel190-001
          server-password: ${{ secrets.PASSWORD }}
